In [4]:
import numpy as np
import time

In [3]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [19]:
size = 1_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end-start} seconds")

python list time = 5.9873762130737305 seconds
numpy array time = 0.043981075286865234 seconds


In [20]:
#memory
import sys

print (f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print (f"numpy array size = {np_arr.nbytes} bytes")

python list size = 8000056000000 bytes
numpy array size = 8000000 bytes


In [2]:
#2D array
import numpy as np
arr2D = np.array([ [1,2,3], [4,5,6,], [7,8,9] ])
print (arr2D, type(arr2D), arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


In [9]:
#create
arr1 = np.zeros((2,3), dtype="int64")
print (arr1, arr1.shape)

arr2 = np.ones((5, ))
print (arr2, arr2.shape)

arr3 = np.full((3,4), 75)
print (arr3, arr3.shape)

arr4 = np.eye(3) # identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0,11,2) # range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4) # evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[75 75 75 75]
 [75 75 75 75]
 [75 75 75 75]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [12]:
# properties
arr = np.array([ [1,2,3], [4,5,6], [7,8,9,] ] )

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.shape)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] (3, 3)


In [16]:
#operations on arrays

arr = np.array([ [1,2,3], [4,5,6] ])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattened = arr.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [18]:
# indexing
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1,2,3], [4,5,6]])

print(arr[0])
print(arr[3])

print(arr2[0][0])
print(arr2[1][1])


1
4
1
5


In [22]:
#fancy Indexing
arr = np.array([1, 2, 3, 4, 5])

idx = [0,1,3]
print(arr[idx])

print(arr[arr>2])     # Boolean Indexing
print(arr[arr % 2 == 0])   # Boolean Indexing
print(arr[arr % 2 != 0])   # Boolean Indexing

[1 2 4]
[3 4 5]
[2 4]
[1 3 5]


In [23]:
# Slicing
arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [25]:
# copy vs view
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print (sub_list)  # Copy
print (nums)

# =====xxxx======xxxx=======xxxxxx======xxxxxx=====xxx====xxx=======xxx===xxxx====

arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0] = 105

print(sub_arr)   # View
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[105   3]
[  1 105   3   4   5]


In [26]:
#Data Types

arr = np.array([1,2,3,4,5])

print(arr, arr.dtype)

[1 2 3 4 5] int64


In [28]:
#Data Types

arr1 = np.array([3 + 5j]) # complex number 
arr2 = np.array([2 + 3j]) # complex number

print(arr1 + arr2) 
print(arr1 - arr2)

[5.+8.j]
[1.+2.j]


In [31]:
#Data Types
# heterogeneous values 
arr = np.array(["Roy", {1,2,3},3.14])

print(arr, arr.dtype)

['Roy' {1, 2, 3} 3.14] object


In [38]:
# multi-dimensional arrays
aee2D = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_colums = np.sum(arr2D, axis = 0)
print(sum_of_colums)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [44]:
#3D array

arr3D = np.array([[[1,2], [3,4], [5,6]], [[7,8], [9,10], [11,12]]])   # 2 x 3 x 2

print(arr3D, arr3D.shape)

#indexing
print(arr3D[1,1,0])

#slicing
print(arr3D[:,0,:])
print(arr3D[:,:,1])

arr3D[:,0,:] = 74 # manupulating data

print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 2  4  6]
 [ 8 10 12]]
[[[74 74]
  [ 3  4]
  [ 5  6]]

 [[74 74]
  [ 9 10]
  [11 12]]]


In [46]:
# vectorization

arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr**2)
print(arr+10)
print(arr+arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [47]:
# broadcasting

arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])

print(arr.shape)
print(arr.shape)

print(arr + arr2)

(5,)
(5,)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [49]:
#normalize

arr = np.array([[1,2], [3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
